import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class Day8Test {

    @Test
    void countAntinodes() {
        var input = """
                ............
                ........0...
                .....0......
                .......0....
                ....0.......
                ......A.....
                ............
                ............
                ........A...
                .........A..
                ............
                ............
                """;
        var grid = Day8.parseInput(input);
        assertEquals(14, Day8.countAntinodes(grid, false));
    }

    @Test
    void countAntinodesResonantFrequency() {
        var input = """
                ............
                ........0...
                .....0......
                .......0....
                ....0.......
                ......A.....
                ............
                ............
                ........A...
                .........A..
                ............
                ............
                """;
        var grid = Day8.parseInput(input);
        assertEquals(34, Day8.countAntinodes(grid, true));
    }

    @Test
    void countAntinodesResonantFrequency_simple() {
        var input = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
                """;
        var grid = Day8.parseInput(input);
        assertEquals(9, Day8.countAntinodes(grid, true));
    }

    @Test
    void countAntinodesResonantFrequencyMaybe() {
        assertEquals(6, Day8.countAntinodes(Day8.parseInput("..xx.."), true));
        assertEquals(6, Day8.countAntinodes(Day8.parseInput("""
                .
                .
                x
                x
                .
                .
                """), true));
        assertEquals(5, Day8.countAntinodes(Day8.parseInput("""
                ...............
                ...............
                ..x............
                ...............
                ....x..........
                ...............
                ...............
                ...............
                ...............
                """), true));
    }
}